### ISSUE TITLE
Junkyard of noobs

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [GenisysPro/GenisysPro#1029]
I'm leaving this fork, I cant belive I even helped them. I will start a private fork soon.
Why I leave? Any kid who come here become dev, and show off. I'm not a dev, but I think I'm better than most of genisyspro devs. If you are a noob copypaster stfu. We all know who are noob devs.

Why I'm not a dev? Because wen I make something I need, I document myself from internet, and I'm not making stuff just by knowing all api by miracle, like real devs from here say. And I do all in my pc, not GitHub, I made GitHub to report stuff wen I first started my server.

Bye!!!!!

This is not a drama or something like that, I just had enough. That's all.
Chatting with stupid ppl = You become stupid yourself. So I just don't wanna to lose more brain cells.

**Comment by Leo3418** [comment]
Who knows their age, but many of our contributors, especially some of those who have sent many pull requests, don't follow rules or guidelines. Many pull requests have no description, are untested, and are not following coding guidelines.
I was trying to impose quality control on this project, like issue and pull request templates, code quality, well-written commit messages, etc.. Unfortunately, only one out of twenty might follow the templates, one out of ten would spend some time write detailed summary for their commits. More ironically, even some GenisysPro members were not doing proper things: some people in the organization wrote nonsense commit messages, did not test their commits so that CI test failed, and made all of their changes on GitHub web editor.
I did not wish to enforce policies on contributing because I thought GenisysPro should be a free software project where everyone can participate in this project with the greatest extent of freedom. Obviously, I was wrong. Unless I apply very strict regulations on contributing, contributors will not change any of their bad contributing habits.

**Comment by jasonwynn10** [comment]
ooh, so you're going to start denying people like dk does on his project?
