### ISSUE TITLE
console warning 

### ISSUE THREAD

**Issue by mote166** [GenisysPro/GenisysPro#36]
#### Issue description

players get teleported back when they sprint on a slab block and this spams the console
#### Steps to reproduce the issue

sprint on a slab block and you will be teleported back and the console will say (ur name) moved wrongly! .
#### OS and versions

* Genisys: just downloaded it from the master branch today
* PHP:7.0.11
* Server OS: linux
* Game version: 1.0.8 (android)

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
Server thread/WARNING]: FAHADQz moved wrongly! 13.05 18:28:12 [Server] INFO [Server thread/WARNING]: iikiritokun13 moved wrongly! 13.05 18:28:12 [Server] INFO [Server thread/WARNING]: YoYoX8GAMER moved wrongly! 13.05 18:28:12 [Server] INFO [Server thread/WARNING]: iikiritokun13 moved wrongly!
```

**Comment by SuperXingKong** [comment]
Anti-cheat system caused this.
Plz edit 'allow-movement-cheats' to 'true' in pocketmine.yml.
This feature will remove soon.

**Comment by SuperXingKong** [comment]
Edit config to prevent it first.
Fixture needs more time.

**Comment by mote166** [comment]
done . but leave this issue open until its permanently fixed .

**Comment by SuperXingKong** [comment]
Ok

**Comment by RTGDaCoder** [comment]
I honestly think that the developers should make it "true" in the PocketMine.yml itself. It's always a good practise to use Boolean functions for the OOP structure itself so we can actually use the correct function to disable it automatically using a function() in the plugin itself rather than editing the Boolean ourselves. Perhaps, this should be implemented or enhanced in MCPE 1.1.0. I'd suggest you to make a separate branch for it where it supports different protocols to ease our life.

**Comment by caspervanneck** [comment]
@mote166  @SuperXingKong  fixt at #249 try it first dont merge whit out testing (;

**Comment by DerddyDert** [comment]
I am closing this as an issue as it is on a to-do project.

**Comment by Pizzahaet** [comment]
Anticheat should be handled by plugin developers not the server....
