### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by TheDiamondYT1** [GenisysPro/GenisysPro#400]
This is just a question as i do not understand... Please don't take this personally, i like to rant.

### Why?
Why do you develop this when you could just contribute to PMMP? Half the contributions might not be accepted due to many people making PRs to this repo with simple changes.

It's harder for plugin developers; you create a plugin for PMMP and you get people complaining it doesn't work then after a while you **finally** get them to send a console log and you can see it's GenisysPro and you've just wasted your time on some kid playing with other server softwares.

So you want to add more commands... Make a pull request god dammit. 

Is it that you like to be in control of the repo and software? I'm the same, but not everyone can control everything. **Life's hard. Deal with it.**

**Comment by TDMidkwhatisxd** [comment]
PMMP , is unstable and corrupt worlds.

**Comment by BajanVlogs** [comment]
Lol dude PMMP is really bad nothing works GenisysPro is the best software out there I'm not just saying that because I work for it it's just really good

You have stable worlds,working beacons,working mobs,working spawners

**Comment by BajanVlogs** [comment]
@Leo3418 why Label this

**Comment by DerddyDert** [comment]
PMMP devs should work on GenisysPro perhaps. GenisysPro is the direct line of Genisys which was the best alternative to Pocketmine. More blocks more vanilla than Pocketmine. We are continuing the legacy of Genisys. PMMP continues the legacy of Pocketmine.

Why do so many top servers(average 200+ simultaneous players) prefer GenisysPro over PMMP?

**Comment by DerddyDert** [comment]
@BajanVlogs it was technically a question. haha

**Comment by BajanVlogs** [comment]
@DerddyDert i find it hate
lol

**Comment by DerddyDert** [comment]
Last thing. Plugin devs could say the same when kids using PMMP which has less features and wonder why a plugin wont work when they created and tested it on GenisysPro.

**Comment by Leo3418** [comment]
Why are there many GNU/Linux distributions, instead of only one distribution? Why don't developers of Ubuntu choose to contribute to Debian, or developers of CentOS choose to contribute to Fedora?
It is because of **diversity**. GenisysPro has several special features that developers of PMMP might never add to their work. One of the most useful feature is integrated DevTools, which makes plugin development easier, since you don't need to find that dedicated plugin and install it.
BTW, please post questions that isn't directly related to development in our forum or Discord chat, not here in GitHub Issues.

**Comment by DerddyDert** [comment]
@Leo3418 knows whats up. Like a boss. haha

**Comment by BajanVlogs** [comment]
@TheDiamondYT1 Trying to takedown our network your doing some illigal crap

**Comment by Pizzahaet** [comment]
@BajanVlogs Shut up fucking degenerate you are lucky to have anyone even semi liking you after all the lies you have been exposed for and what the hell makes you think it is him doing the ddos attacks, you don't know not a damn thing about developing let alone networking, you said you were going to do me ages ago my I.P. has been on my Twitter for ages, you also got my IP from your multicraft server, my internet has been running smoothly since you threatened to ddos me... If anything GenisysPro is maybe 5th place of server software spoon/forks of pmmp...

**Comment by MasterOfTheRealm** [comment]
@Pizzahaet Can you two honestly stop fighting among yourselves?
