### ISSUE TITLE
Missing crafting recipes

### ISSUE THREAD

**Issue by ibookcc** [GenisysPro/GenisysPro#409]
> # 描述
> 大量合成公式缺失
> 例如：玻璃板，玻璃瓶
> （这只是举例，事实上远远不止这么多）
> 如果你们可以告诉我在哪修改可以添加
> 我很乐意帮助你们维护这个核心
> 我会一些php和OO风格代码格式

> # description
> Many crafting recipes are missing
> For example: glass plates, glass bottles
> (these are just some examples.In fact, far more than that)
> if you can tell me where to change it.I can add it
> I know some PHP code and OO style.
> I'd be happy to help you build up this core

# environment

- 2017 x86_64
- PHP：7.0.9
- Zend：3.0.0
- OS：Linux, CentOS7.2

**Comment by Leo3418** [comment]
https://github.com/GenisysPro/GenisysPro/blob/master/src/pocketmine/resources/recipes.json
等您修改完了，可以给我们发pull request。
When you've done, you may send us a pull request.  

附注：如果您英语不好，请直接用中文书写题目，不要使用机器翻译，因为翻译出来的文字，英语母语使用者都很难看明白，往往只有懂中文的才能反推每个单词的中文原文，然后理解题目的意思。然后，我们会把您的中文题目翻译成英文。
PS: If you aren't proficient in English, please just write your title in Chinese, instead of using a machine translator, since the outcome of the translator can hardly be understood by English native speakers. Only those who understand Chinese can guess the original Chinese phrase corresponding to each English word in your title and hence understand it. Then we will translate your Chinese title into English.

**Comment by ibookcc** [comment]
@Leo3418 fine, i got it.So, does this problem can be solved?

**Comment by ibookcc** [comment]
@Leo3418 sorry, because i send to much text in a short time to save my time.I forget it, and use the machine to translate.

**Comment by SuperXingKong** [comment]
此bug已在最近几个Commit中被修复,请使用最新版本的GenisysPro.

**Comment by Leo3418** [comment]
@ibookcc we'll investigate this issue recently. You said that you have some knowledge of PHP, and you'd like to help us, so you can fix it and send us a pull request.
