### ISSUE TITLE
Add support for mcpe 1.2

### ISSUE THREAD

**Issue by itabxt** [GenisysPro/GenisysPro#714]
#### Platform information

* Git commit:

* PHP binary version:

* Server OS:

* Game client:

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by DerddyDert** [comment]
Mcpe 1.2 is not released yet. It won't be in master branch until its released.

**Comment by itabxt** [comment]
That's why this project cannot be the leader project.

**Comment by Leo3418** [comment]
@itabxt Nowadays many software companies, like Microsoft and Google, are releasing beta/testing versions of their software projects, such as Windows Insiders, Android Developer Preview, etc. These testing branches allow their users to try out upcoming new features, which is very attractive and is a major reason that people are glad to use those testing versions. 

Unfortunately, there's a common misconception on testing software: these beta versions are OK for production use, a.k.a being used as a daily driver. Software developers always want to ship a stable version of their work to their end users. Beta versions are exception, because their sake is to help making **the release versions of software** more stable, not to make beta versions themselves more stable. The testing branches are very likely to be unstable and malfunctioning, but developers are still releasing them, merely for the purpose of collecting more bug info before the formal release and letting developers get ready for the new version, **not for you guys who think that testing versions are OK for daily use**.

We DO NOT encourage any player who REALLY play this game to use 1.2 Beta, since it tends to be unstable and problematic. That's why we are responsible for our users, not why this project cannot be the leader project.

**Comment by itabxt** [comment]
as you wish
