### ISSUE TITLE
Toolbox effect

### ISSUE THREAD

**Issue by HipsterAF** [GenisysPro/GenisysPro#880]
#### Issue description

Toolbox gives player to add effects on them, and server doesn't remove them, please fix

#### Platform information

* Git commit: 6b1ef89

* PHP binary version: 7.2

* Server OS: Linux

* Game client: MCPE V1.1

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```
NONE
```

**Comment by MasterOfTheRealm** [comment]
Well, toolbox effects are from the client end. They don't force effects into the server itself. But some effects like Night Vision, Jump Boost, Speed and Haste will work because those instances are from the client itself and can be manipulated by a third party client to some extent. Best thing to do is use an anticheat plugin to prevent some of those client side effects.

**Comment by HipsterAF** [comment]
Well i dont know any anticheat plugin that provides this features, any suggestions?
