### ISSUE TITLE
Add Slapper plugin compatibility

### ISSUE THREAD

**Issue by EmreTr1** [GenisysPro/GenisysPro#95]
Slapper plugin not working on genisysPRO

**Comment by caspervanneck** [comment]
Wait for slapper update

**Comment by caspervanneck** [comment]
Or its pmmp plugin

**Comment by Leo3418** [comment]
Thanks for the suggestion. As a general-purpose MCPE server software, GenisysPro is not, and should not be designed specifically for a certain plugin. Please directly ask developer of the plugin your mentioned for any support. Should you find any bug or problem that is *plugin-independent*, which means that the bug affects more than one specific plugin, we welcome you to submit a issue.

**Comment by DerddyDert** [comment]
@jojoe77777

**Comment by DerddyDert** [comment]
There is a better written plugin than slapper. Ill post it here when I get a chance.

**Comment by DerddyDert** [comment]
@EmreTr1 @caspervanneck Does this work on current src?

**Comment by DerddyDert** [comment]
@caspervanneck @SuperXingKong GenisysPro has a lot of unique code as this is not simply a cut n paste spoon and is becoming far more advanced than PMMP. With that being the case we need to provide some support for the mainstream plugins and aim toward backward compatibility. The only reason a plugin shouldn't work on GenisysPro that does on PMMP should be due to specific advancements we have beyond them.

**Comment by SuperKali** [comment]
@EmreTr1 slapper work on my server 

* [Slapper-GenisysPro.zip](https://github.com/GenisysPro/GenisysPro/files/1092092/Slapper-GenisysPro.zip)
